server:
  port: 9999

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/khubebanjare/config-server-configuration-files.git
          clone-on-start: true
          
#  security:
#    user:
#      name: khubebanjare
#      password: kh13@u04#be195*K!~

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

#actuator
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'