server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
#actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: discover-service